software:
  refresh_period_s: 30

device:
  name: "MyLinuxDevice"
  manufacturer: "DeviceManufacturer"
  model: "DeviceModel"
  serial_number: "xxxxxxxxxxxxxx..."

mqtt_server:
  ip: "192.168.1.XXX"
  port: "1883"
  username: "myuser"
  password: "mypassword"

sensors:
  - name: "CPU Temperature"
    command: "echo CPU"
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
  - name: "Memory Usage"
    command: "free | grep Mem | awk '{print $3/$2 * 100.0}'"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:memory"
  - name: "Disk Usage"
    command: "df / | tail -1 | awk '{print $5}' | sed 's/%//'"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:harddisk"
  - name: "CPU Load"
    command: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:cpu-64-bit"