software:
  refresh_period_s: 30

device:
  name: "MyLinuxDevice"
  manufacturer: "DeviceManufacturer"
  model: "DeviceModel"
  serial_number: "xxxxxxxxxxxxxx..."

mqtt_server:
  ip: "192.168.1.XXX"
  port: "1883"
  username: "myuser"
  password: "mypassword"

sensors:
  - name: "CPU Temperature"
    command: "awk '{print $1/1000}' /sys/class/thermal/thermal_zone0/temp"
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
  - name: "Memory Usage"
    command: "free | awk '/Mem/{printf(\"%.2f\", $3/$2 * 100.0)}' | cut -d'%' -f1"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:memory"
  - name: "Disk Usage"
    command: "df -h | awk '/\/$/ {print $5}' | cut -d'%' -f1"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:harddisk"
  - name: "CPU Load"
    command: "top -bn1 | awk '/Cpu/ { print $2}'"
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:cpu-64-bit"